create table "public"."user_pairs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_a" uuid not null,
    "user_b" uuid not null
);


alter table "public"."user_pairs" enable row level security;

CREATE UNIQUE INDEX user_pairs_id_key ON public.user_pairs USING btree (id);

CREATE UNIQUE INDEX user_pairs_pkey ON public.user_pairs USING btree (user_a, user_b);

alter table "public"."user_pairs" add constraint "user_pairs_pkey" PRIMARY KEY using index "user_pairs_pkey";

alter table "public"."user_pairs" add constraint "public_user_pairs_user_a_fkey" FOREIGN KEY (user_a) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_pairs" validate constraint "public_user_pairs_user_a_fkey";

alter table "public"."user_pairs" add constraint "public_user_pairs_user_b_fkey" FOREIGN KEY (user_b) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_pairs" validate constraint "public_user_pairs_user_b_fkey";

alter table "public"."user_pairs" add constraint "user_pairs_id_key" UNIQUE using index "user_pairs_id_key";

grant delete on table "public"."user_pairs" to "anon";

grant insert on table "public"."user_pairs" to "anon";

grant references on table "public"."user_pairs" to "anon";

grant select on table "public"."user_pairs" to "anon";

grant trigger on table "public"."user_pairs" to "anon";

grant truncate on table "public"."user_pairs" to "anon";

grant update on table "public"."user_pairs" to "anon";

grant delete on table "public"."user_pairs" to "authenticated";

grant insert on table "public"."user_pairs" to "authenticated";

grant references on table "public"."user_pairs" to "authenticated";

grant select on table "public"."user_pairs" to "authenticated";

grant trigger on table "public"."user_pairs" to "authenticated";

grant truncate on table "public"."user_pairs" to "authenticated";

grant update on table "public"."user_pairs" to "authenticated";

grant delete on table "public"."user_pairs" to "service_role";

grant insert on table "public"."user_pairs" to "service_role";

grant references on table "public"."user_pairs" to "service_role";

grant select on table "public"."user_pairs" to "service_role";

grant trigger on table "public"."user_pairs" to "service_role";

grant truncate on table "public"."user_pairs" to "service_role";

grant update on table "public"."user_pairs" to "service_role";


